#!/usr/bin/env bash
# script to install and setup nginx
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
service nginx start
